version: '2'
services:
  db:
    build: ./docker/database/
    volumes:
      - postgres:/var/lib/postgresql/data:rw
  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
  statsd:
    image: python:2.7.13
    volumes:
      - .:/opt/rowboat
    command: python /opt/rowboat/docker/nulld.py
    ports:
      - "8125:8125"
    stop_signal: SIGKILL
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    ports:
      - "8686:8686"
    depends_on:
      - db
      - redis
      - statsd
  frontend:
    build: ./frontend/
    environment:
      - NODE_ENV=docker
    command: npm run serve
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - "8888:8080"
    depends_on:
      - web
  bot:
    build: .
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/rowboat
    ports:
      - "7171:7171"
    depends_on:
      - web
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web
volumes:
  postgres: {}
